### ISSUE TITLE
Hide wall of "No syntax errors detected in..." ?

### ISSUE THREAD

**Issue by carcinocron** [brodkinca/BCA-Laravel-Inspect#11]
Pretty much the only reason I don't use the lint feature of this repo is because it's just easier to copy this command from my notepad. 

```
find ~/www/InstanceOfMichael/app -name '*.php' -exec php -l {} \; | grep -v "No syntax errors detected in"
```

I don't really see how useful it is to know that 300 files have "no syntax errors" when you're trying to find the 1 or 2 that do.

**Comment by brodkin** [comment]
Newer versions of PHP have changed the output to be more in line with the request of this PR. Closing since this PR is no longer needed.
